name: Python CI/CD Pipeline
 
on:
  push:
    branches:
      - main
      - developer
      - feature
      - feature/*
  pull_request:
    branches:
      - main
      - develop
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
 
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
 
    - name: Install Dependencies
      run: pip install -r requirments.txt
 
    - name: Run Tests
      run: pytest
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
 
    steps:
    - name: Deploy Application
      run: echo "Deploying application to production"
